name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: nshkuta
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push using docker-compose
      uses: docker/compose@main 
      with:
        services: app
        file: ./docker-compose.yml
        push: true
        tags: ghcr.io/nshkuta/your-repo:latest
